version: '3.8'

services:
  vqasynth_base:
    build:
      context: ../
      dockerfile: docker/base/Dockerfile  # Dockerfile for the vqasynth:base image
    image: vqasynth:base  # Tag the built image as vqasynth:base
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  embeddings_stage:
    build:
      context: ../
      dockerfile: docker/embeddings_stage/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  filter_stage:
    build:
      context: ../
      dockerfile: docker/filter_stage/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - embeddings_stage
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  depth_stage:
    build:
      context: ../
      dockerfile: docker/depth_stage/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - filter_stage
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  location_refinement_stage:
    build:
      context: ../
      dockerfile: docker/location_refinement_stage/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - caption_stage
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  scene_fusion_stage:
    build:
      context: ../
      dockerfile: docker/scene_fusion_stage/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - location_refinement_stage
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  prompt_stage:
    build:
      context: ../
      dockerfile: docker/prompt_stage/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - scene_fusion_stage
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]
