version: '3.8'

services:
  filter_processor:
    build:
      context: ../
      dockerfile: docker/filter_processor/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  depth_processor:
    build:
      context: ../
      dockerfile: docker/depth_processor/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - filter_processor
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  segment_processor:
    build:
      context: ../
      dockerfile: docker/segment_processor/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - caption_processor
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  pointcloud_processor:
    build:
      context: ../
      dockerfile: docker/pointcloud_processor/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - segment_processor
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  prompt_processor:
    build:
      context: ../
      dockerfile: docker/prompt_processor/Dockerfile
    volumes:
      - ${IMAGE_DIR}:${IMAGE_DIR}
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - pointcloud_processor
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]
