version: '3.8'

services:
  embeddings_stage:
    build:
      context: ../
      dockerfile: docker/embeddings_stage/Dockerfile
    volumes:
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      HF_TOKEN: ${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  filter_stage:
    build:
      context: ../
      dockerfile: docker/filter_stage/Dockerfile
    volumes:
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - embeddings_stage
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      HF_TOKEN: ${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  location_refinement_stage:
    build:
      context: ../
      dockerfile: docker/location_refinement_stage/Dockerfile
    volumes:
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - filter_stage
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      HF_TOKEN: ${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  scene_fusion_stage:
    build:
      context: ../
      dockerfile: docker/scene_fusion_stage/Dockerfile
    volumes:
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - location_refinement_stage
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      HF_TOKEN: ${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  prompt_stage:
    build:
      context: ../
      dockerfile: docker/prompt_stage/Dockerfile
    volumes:
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - scene_fusion_stage
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      HF_TOKEN: ${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]

  r1_reasoning_stage:
    build:
      context: ../
      dockerfile: docker/r1_reasoning_stage/Dockerfile
    volumes:
      - ${OUTPUT_DIR}:${OUTPUT_DIR}
    depends_on:
      - prompt_stage
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      HF_TOKEN: ${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: ["gpu"]
